# Generated by Django 4.2.3 on 2023-07-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_side', models.BooleanField(default=True)),
                ('text', models.TextField(max_length=500)),
                ('category', models.IntegerField(choices=[(0, 'Start of conversation'), (1, 'Ask wine'), (2, 'Common')])),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.conversation')),
            ],
        ),
    ]
