# Generated by Django 4.2.3 on 2023-07-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_conversation_utterance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineRecommendation',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.utterance')),
            ],
        ),
    ]
