# Generated by Django 4.2.3 on 2023-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_winerecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utterance',
            name='category',
        ),
        migrations.AddField(
            model_name='conversation',
            name='stage_history',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utterance',
            name='ai_side',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utterance',
            name='time_to_response',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='user_side',
            field=models.TextField(blank=True, null=True),
        ),
    ]
