# Generated by Django 4.2.3 on 2023-07-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_remove_utterance_category_conversation_stage_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utterance',
            name='text',
        ),
    ]
