# Generated by Django 4.2.3 on 2023-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_remove_utterance_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='stage_history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='ai_side',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='user_side',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
