# Generated by Django 4.2.3 on 2023-07-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0006_alter_conversation_stage_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='winerecommendation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ChatExamples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('example', models.TextField(blank=True, max_length=500, null=True)),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.utterance')),
            ],
        ),
    ]
